### PR TITLE
changed the Logo!

### PR DESCRIPTION
**Pull request by Sanket2055**
changed the logo from institute logo to [this](https://ibb.co/p1FG6v1) , if u think this pr is appropriate please merge it and add the label hacktoberfest-accepted thank you !!

### CODE REVIEW

**Comment by TheNinza** [comment]
@Sanket2055, The color scheme of the logo must resemble the color scheme of the website. So It would be great if you can change it. Also DON'T host the logo somewhere else. Add it in src/assets folder

**Comment by Sanket2055** [comment]
> @Sanket2055, The color scheme of the logo must resemble the color scheme of the website. So It would be great if you can change it. Also DON'T host the logo somewhere else. Add it in src/assets folder

thanks for the reply sir , so should i change the text color  inside the logo to  violet -blue(same as the navbar ) or should i also  change the  icon (orange one ) to other icon and  text formatting .
thank you!

**Comment by TheNinza** [comment]
@Sanket2055 you don't need to be this much formal :) . Keep the conversation simple. speaking of changes, whatever you add must follow the theme... that's all.

**Comment by Sanket2055** [comment]
> @Sanket2055 you don't need to be this much formal :) . Keep the conversation simple. speaking of changes, whatever you add must follow the theme... that's all.

okay sir

**Comment by TheNinza** [comment]
hey @Sanket2055 , There is a conflict due to  the last merge... resolve that too...

**Comment by Sanket2055** [comment]
Hello @TheNinza  sir , what do u think about  [this](https://ibb.co/YT50vD5) logo

**Comment by TheNinza** [comment]
hey @Sanket2055 , sorry for the delay from my side. Yes the logo looks good. Make sure you resolve the conflicts before making the pr.

**Comment by Sanket2055** [comment]
@TheNinza sir , please review this, I have added the logo ( resolved the conflicts )

**Review by TheNinza — CHANGES_REQUESTED** [review]
Use svg image rather than png also increase the height to about 70px

**Comment by Sanket2055** [comment]
@TheNinza sir , in case of  height=70 the logo  was getting  overflowed in responsive mode , height 64 seemed perfect so changed it to 64.

**Review by TheNinza — APPROVED** [review]
Looks good. Merging

**Comment by Sanket2055** [comment]
@TheNinza sir can u please add the label  hacktober-fest accepted  to this PR , Thank you!

**Comment by TheNinza** [comment]
@Sanket2055 already did

**Comment by Sanket2055** [comment]
> @Sanket2055 already did

ohh okay sir, it was showing label as none .that's  why i  asked

**Pull request merged**
